scrape_configs:
  - job_name: 'snmp'
    static_configs:
      - targets:
        - snmp-host  # SNMP device.
        - snmp-test # SNMP device.
        - clab-routers-router1
        - clab-routers-router2
    metrics_path: /snmp
    params:
      auth: [public_v2]
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp-exporter:9116  # The SNMP exporter's real hostname:port.
  - job_name: 'promsnmp'
    scrape_interval: 60s  # SNMP polling interval
    static_configs:
      - targets:
          - 'promsnmp:8080'  # Replace with your SNMP device IP
    metrics_path: /promSnmp/sample
  - job_name: 'promsnmp-route'
    scrape_interval: 60s  # SNMP polling interval
    static_configs:
      - targets:
          - 'promsnmp:8080'  # Replace with your SNMP device IP
    metrics_path: /promSnmp/router

  - job_name: 'promsnmp-direct'
    scrape_interval: 60s  # SNMP polling interval
    static_configs:
      - targets:
          - 'promsnmp:8080'  # Replace with your SNMP device IP
    metrics_path: /promSnmp/direct


